name: Build Docker Image on PR

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: List files in repo
        run: ls -la

      - name: Build Docker image with debug
        run: docker build --progress=plain -t my-app-image:pr-${{ github.event.pull_request.number }} .
