name: Build Docker Image on PR

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: List files in repo
        run: ls -la

      - name: Logout from Docker (if logged in previously)
        run: docker logout

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image (frontend)
        run: docker build --progress=plain -t ghcr.io/valenh5/Frontend---Uavdocx/frontend-app:pr-${{ github.event.pull_request.number }} .


      - name: Push Docker image to GHCR
        run: docker push ghcr.io/valenh5/Frontend---Uavdocx/frontend-app:pr-${{ github.event.pull_request.number }}
